# Etapa 1: Build da aplicação
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Etapa 2: Imagem final
FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
# Copia o arquivo ormconfig.json se existir
COPY --from=builder /app/ormconfig.json ./ormconfig.json
EXPOSE 3000
CMD npm run migration:run && node dist/main
